name: Deployment Flow 1
on: [push]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
      uses: actions/checkout@v3
      # a "with" keyword may be needed if there are 
      # dependencies to are needed for a specified 
      # "action"
      # a runner might not have the dependencies
      # if it isn't installed
      - name: Install NodeJS
      uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Install dependencies
        # npm ci is safer than npm install
        run: npm ci
      - name: Lint
        run: npm run lint
      - name: Test code
        run: npm test
      - name: Build project
        run: npm run build
      - name: Deploy
        run: echo "Deploying project"